### ISSUE TITLE
llama 3.2 vision not working

### ISSUE THREAD

**Issue by lustfeind** [stavsap/comfyui-ollama#72] opened 2024-11-25 14:03 UTC
What I'm doing wrong? 

FETCH DATA from: /Users/pmm17200/Documents/pinokio/api/comfy.git/app/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]
HTTP Request: GET http://127.0.0.1:11434/api/tags "HTTP/1.1 200 OK"
got prompt
[Ollama Vision]
request query params:

- query: describe the image shortly
- url: http://127.0.0.1:11434
- model: llama3.2-vision:latest

!!! Exception during processing !!! Error calling function `serialize_model`: OSError: [Errno 63] File name too long: 'iVBORw0KGgoAAAANSUhEUgAAAwAAAAIACAIAAAC6lJxtAAEAAElEQVR4nEz9abOtaXYchmWu9bz73KGqu6t6QgNggwCIgSAEgQQpMhjiLE427QjbX/z3HGFH+KtDEQ6ZIsOiKEshi4JImoMAggQxo6fqGm7de85+n7XSH3K9p7r6Q1ffvmefvd/9DLkyc+Xi/nv/WUGpWg1BJG1G0FBAB+Og4QIIDJULUZ0N5EQSq3u3qVIBPN2y+OlKACNYADAilwrY98PNkQSQH.............

**Comment by stavsap** [comment] 2024-11-25 16:08
looks like some os related error, but why is you filename is so huge?

**Comment by lustfeind** [comment] 2024-11-25 16:22
I've no idea. My image to described has a short filename. I don't know was is this in the terminal. Looks like the entire file content is give as base64 encoded string or something like that.  
btw., I'm using comfyUI with pinokio.ai on my mac silicon m1 pro machine.

**Comment by pphoto808** [comment] 2024-11-25 17:33
Same problem on Mac M2 Ultra. It's definitely Mac related. Somewhere the file name is being translated into this HUGE string of text.

**Comment by stavsap** [comment] 2024-11-25 20:28
can you share the full terminal log? ill try to help if it's related to the code in this repo

**Comment by pphoto808** [comment] 2024-11-26 03:43
I went back to check how many characters that string of text was. I pasted it to Page document. I stop counting at 55 pages, 1 inch borders sides and bottom. Here is the start:

Traceback (most recent call last):
  File "/Volumes/Extreme_Pro/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Extreme_Pro/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Extreme_Pro/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/Volumes/Extreme_Pro/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Extreme_Pro/ComfyUI/custom_nodes/comfyui-ollama/CompfyuiOllama.py", line 80, in ollama_vision
    response = client.generate(model=model, prompt=query, images=images_b64, keep_alive=str(keep_alive) + "m", format=format)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/ollama/_client.py", line 256, in generate
    ).model_dump(exclude_none=True),
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.12/site-packages/pydantic/main.py", line 421, in model_dump
    return self.__pydantic_serializer__.to_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Error calling function `serialize_model`: OSError: [Errno 63] File name too long: 'iVBORw0KGgoAAAANSUhEUgAAAcMAAAJECAIAAADludh0AAEAAElEQVR4nHT92bodyZEmitngHhFr3DM2gERmMslkkcWqbqrUp78+0oWGWz2GnkcPogeQrqQrffqOdLpb59RAskjmnAkgAexxjTG4u5kufIjYqD67KkFg7VgRHu5mv/02uDn+X/6v/3dCJEIiZiImQgQAQEIEGHzYH1tEsoa7vgfQ9XJZVxUxMRECIQMqKKAKAEPFhhEVNQRt+77tOkIWDYP3hs1s1swqa4gAgYkMMTMikJegAKAiCvn/IHhx3u8P7cNmsz8chmFwgxuG4dAe97vddvt43D327W5o94fNTbu7U1Q2xLZ+8cXvf/P3/+mTTz65vro6P1nPqsoaJkYA8D4c2v7m7m6z265WJ5WtDof2p9ev/Wf/PNT/8EcmTSw35/bDsVZYtsGAAB8O

**Comment by hortom** [comment] 2024-11-27 09:03
This text `iVBORw0KGgoAAAANSUhEUgAAAcMAAAJECAIAAADludh...` is the binary encoded file itself instead of the file URL. That is why it is too long.
About the "How it happened", I can't answer. But if I decoded this part correctly, it is a PNG image, maybe with 451x580 resolution.
I hope this helps to debug it further.

**Comment by aecirli** [comment] 2024-11-27 10:41
Having the same problem on Mac M1 max. It's not just vision model, I am unable to run any LLM models inside Comfyui.
I can run them in the terminal without a problem.

**Comment by el0911** [comment] 2024-11-28 11:06
![Screenshot 2024-11-28 at 11 05 22](https://github.com/user-attachments/assets/510b9397-a02f-4540-b9b4-af4a535fdc9f)
tested my suspicion and made a google collab to test the ollama client it did not work also so the issue is from the ollama client let me try downgrading further

**Comment by el0911** [comment] 2024-11-28 11:18
switching out the ollama and using simple API calls seems to work 
![Screenshot 2024-11-28 at 11 13 07](https://github.com/user-attachments/assets/3b78b4d2-1fd6-4efa-adb0-ae64aad01700)
![Screenshot 2024-11-28 at 11 16 34](https://github.com/user-attachments/assets/2db3bfde-3b9c-4999-a195-74cf7d92df79)
And the response is. 
![Screenshot 2024-11-28 at 11 17 32](https://github.com/user-attachments/assets/3c4dddff-5515-4255-a474-bee34e6835ae)
So even going back on ollama to 0.3.1 the mother****** did not work so my postulation is a library ollama uses got updates and causing the issue, let me experiment a bit more **** this ***t

**Comment by el0911** [comment] 2024-11-28 11:30
![Screenshot 2024-11-28 at 11 30 14](https://github.com/user-attachments/assets/0af5b468-17ae-4825-8137-443cf83e3e00)
well now I know where the `serialize_model ` function is and the cause of all our pain

**Comment by el0911** [comment] 2024-11-28 11:38
looks like the fix has to be in `serialize_model` function this is messed up because well its simple messed up!

**Comment by el0911** [comment] 2024-11-28 12:03
Partial anger irritation and annoyance calmed down now after an episode of rick and morty(not a sponsored ad), look the ollama client seems to have a valid check for `binary` data so instead of encoding it to base 64 let me test it with just binary image data

**Comment by el0911** [comment] 2024-11-28 12:05
![Screenshot 2024-11-28 at 12 03 49](https://github.com/user-attachments/assets/a5b9c76f-7571-4231-97ee-ab73974c994a)
seems to work thank God, ok i would make a pr to the project and temporarily edit the code I have on my server, 3 hours waisted! first time contributing to open source, and I never knew it would be the cause of necessity

**Comment by el0911** [comment] 2024-11-28 12:33
so i cant actually make a pr to this project but here is the fix to the admins 

```

class OllamaVision:
    def __init__(self):
        pass

    @classmethod
    def INPUT_TYPES(s):
        seed = random.randint(1, 2 ** 31)
        return {
            "required": {
                "images": ("IMAGE",),
                "query": ("STRING", {
                    "multiline": True,
                    "default": "describe the image"
                }),
                "debug": (["enable", "disable"],),
                "url": ("STRING", {
                    "multiline": False,
                    "default": "http://127.0.0.1:11434"
                }),
                "model": ((), {}),
                "keep_alive": ("INT", {"default": 5, "min": -1, "max": 60, "step": 1}),
                "format": (["text", "json",''],),
                "seed": ("INT", {"default": seed, "min": 0, "max": 2 ** 31, "step": 1}),
            },
        }

    RETURN_TYPES = ("STRING",)
    RETURN_NAMES = ("description",)
    FUNCTION = "ollama_vision"
    CATEGORY = "Ollama"

    def ollama_vision(self, images, query, debug, url, model, seed, keep_alive, format):
        images_binary = []

        if format == "text":
            format = ''

        for (batch_number, image) in enumerate(images):
            # Convert tensor to numpy array
            i = 255. * image.cpu().numpy()
            
            # Create PIL Image
            img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))
            
            # Save to BytesIO buffer
            buffered = BytesIO()
            img.save(buffered, format="PNG")
            
            # Get binary data
            img_binary = buffered.getvalue()
            images_binary.append(img_binary)

        client = Client(host=url)

        if debug == "enable":
            print(f"""[Ollama Vision]
request query params:

- query: {query}
- url: {url}
- model: {model}

""")

        response = client.generate(model=model, prompt=query, images=images_binary, keep_alive=str(keep_alive) + "m", format=format)

        if debug == "enable":
            print("[Ollama Vision]\nResponse:\n")
            pprint(response)

        return (response['response'],)
```

**Comment by el0911** [comment] 2024-11-28 12:52
Also would love to make the commit @stavsap

**Comment by ParthSareen** [comment] 2024-11-28 20:03
Hey @stavsap - one of the maintainers at Ollama here.

I think the way that the image is being passed into the request is the issue. Would recommend passing in images like so while I roll out a fix on my end to cover this case. It's an edge case for decoding slightly differently.

```py
img = base64.b64encode(Path(path).read_bytes()).decode()
```

Would also recommend pinning the Ollama Python version in the future to not run into silent issues they can be tested before a rollout :)

Will ping when the fix is rolled out on my end

**Comment by ParthSareen** [comment] 2024-11-28 22:31
Just cut a new release - should work! https://github.com/ollama/ollama-python/releases/tag/v0.4.2

**Comment by stavsap** [comment] 2024-11-28 23:37
thank you very much, everyone that is involved, for investigating this issue, i am going to be near a PC only next weekend then i would be able to make the fix.

if any one desires, he/she can fork and make PR and validate it works fine with the new ollama python version, i would be able to review and merge from my mobile.

**Comment by el0911** [comment] 2024-12-02 14:37
Made the Pr @stavsap 
https://github.com/stavsap/comfyui-ollama/pull/73
here are the commit changes
https://github.com/stavsap/comfyui-ollama/pull/73/commits/2136e8a9458ca51704b58ea67601d29f05ca52a3

**Comment by pphoto808** [comment] 2024-12-05 06:04
I think you can safely close this. Just got the update and it works perfectly on my Mac M2 Studio.

**Closed** 2024-12-05 13:41 UTC
Labels: bug

**Comment by lustfeind** [comment] 2024-12-10 19:32
Great job! Thank you!
