### ISSUE TITLE
getting a 'load_duration' and sometimes a 'context' error.

### ISSUE THREAD

**Issue by Appolonius001** [stavsap/comfyui-ollama#23] opened 2024-07-13 03:28 UTC
```
Error occurred when executing OllamaGenerateAdvance:

'context'

File "C:\V\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\V\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\V\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\V\ComfyUI\ComfyUI\custom_nodes\comfyui-ollama\CompfyuiOllama.py", line 255, in ollama_generate_advance
return (response['response'],response['context'],)
~~~~~~~~^^^^^^^^^^^
```
and
```
Error occurred when executing OllamaGenerate:

'load_duration'

File "C:\V\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\V\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\V\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\V\ComfyUI\ComfyUI\custom_nodes\comfyui-ollama\CompfyuiOllama.py", line 129, in ollama_generate
- load_duration: {response["load_duration"]}
~~~~~~~~^^^^^^^^^^^^^^^^^
```
Vision node seems to work but i get the above error with generate advanced & generate

**Comment by alexnikospb** [comment] 2024-07-13 09:48
+ 1,  Today after the update OIlama and Comfyui, started getting this error:
 Error occurred when executing OllamaGenerate:
'load_duration'

**Comment by stavsap** [comment] 2024-07-13 11:23
pushed a fixed to the print, it seems that the response from ollama is changed, API change?

seems also that context in advance is missing, checking this,

**Comment by alexnikospb** [comment] 2024-07-13 12:23
The API has not changed, it connects to the Ollama, but then an error immediately appears. Yesterday everything worked fine with the same circuit and settings. 
From the console:  

HTTP Request: POST http://127.0.0.1:11434/api/generate "HTTP/1.1 200 OK"
!!! Exception during processing!!! 'load_duration'
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-ollama\CompfyuiOllama.py", line 129, in ollama_generate
    - load_duration: {response["load_duration"]}
KeyError: 'load_duration'

**Comment by alexnikospb** [comment] 2024-07-13 13:43
I solved the problem by completely reinstalling

**Comment by KorDum** [comment] 2024-07-13 13:57
It didn't help me. I also tried ComfyUI Ollama YN, same error there

**Comment by alexnikospb** [comment] 2024-07-13 14:10
> It didn't help me. I also tried ComfyUI Ollama YN, same error there

Try change debug: disable in Ollama Generate

**Comment by KorDum** [comment] 2024-07-13 14:35
Also I uninstalled all python dependencies and reinstalled without cache.
The error persisted, the debug flag has no effect on the error :(

**Comment by KorDum** [comment] 2024-07-13 14:37
О! I got it! The problem is in the Advance node, there is no error in the normal node!

**Comment by stavsap** [comment] 2024-07-13 19:40
please update ollama to 0.2.4, it seems their api back to normal

**Comment by KorDum** [comment] 2024-07-14 06:18
The problem was observed just 0.2.4, and 0.2.5 fixes the problem. Thanks!

**Closed** 2024-08-11 18:23 UTC
